import Button from './Button/Button';
import IconSet from './IconSet/IconSet';
import Icon from './Icon/Icon';
import Tooltip from './Tooltip/Tooltip';
import Input from './Input/Input';
import Autocomplete from './Autocomplete/Autocomplete';
import Checkbox from './Checkbox/Checkbox';
import Radio from './Radio/Radio';
import RadioIcons from './RadioIcons/RadioIcons';
import RadioTabs from './RadioTabs/RadioTabs';
import InputDropdown from './InputDropdown/InputDropdown';
import Select from './Select/Select';
import FormRow from './FormRow/FormRow';
import Form from './Form/Form';
import Loading from './Loading/Loading';
import Link from './Link/Link';
export declare const Components: {
    Button: typeof Button;
    IconSet: typeof IconSet;
    Icon: typeof Icon;
    Tooltip: typeof Tooltip;
    Input: typeof Input;
    Autocomplete: typeof Autocomplete;
    Checkbox: typeof Checkbox;
    Radio: typeof Radio;
    RadioIcons: typeof RadioIcons;
    RadioTabs: typeof RadioTabs;
    InputDropdown: typeof InputDropdown;
    Select: typeof Select;
    FormRow: typeof FormRow;
    Form: typeof Form;
    Loading: typeof Loading;
    Link: typeof Link;
};
